# Default values for cnacnf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


prometheus:
  kubeStateMetrics: 
    enabled: false
  nodeExporter:
    enabled: false
  server:
    global:
      scrape_interval: 15s
  pushgateway:
    enabled: false
fluentd-elasticsearch:
  elasticsearch:
    host: "csf-elasticsearch-client"
elasticsearch:
  client:
    replicas: 1
  master:
    replicas: 2
  data:
    replicas: 1
kibana:
  env:
    ELASTICSEARCH_HOSTS: "http://csf-elasticsearch-client:9200"
  ingress:
    enabled: true
    hosts:
      - kibana.cna.in
  testFramework:
    enabled: "false"


