apiVersion: v2
name: cnacnf
description: CNA Common Service Framework Integration Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 0.1.0

appVersion: 1.16.0
dependencies:
- name: prometheus
  version: "11.12.1"
  repository: "https://charts.helm.sh/stable"
- name: prometheus
  version: "11.12.1"
  repository: "https://charts.helm.sh/stable"
  