# Default values for cnacnf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


prometheus:
  kubeStateMetrics: 
    enabled: false
  nodeExporter:
    enabled: false
  server:
    global:
      scrape_interval: 15s
  pushgateway:
    enabled: false

